### ISSUE TITLE
Adding other aesthetics

### ISSUE THREAD

**Issue by JimGrange** [Selbosh/ggChernoff#1]
Thanks for this package. I am using it to create stimuli for a cognitive experiment, so the ability to continuously vary the smile intensity is proving incredibly useful. I am using this to vary the "emotionality" of a stimulus. However, I need to also vary another dimension of the face that is non-emotional. For example, is it possible using this package to also vary eye separation (distance between eyes) procedurally?

Thanks!

**Comment by Selbosh** [comment]
In principle, yes, but it would require a pull request, parametrizing `eyesGrob`, which is currently hard-coded to horizontal positions of `c(.3, .7)` to accept a continuous argument, as `browGrob` does for `brow`, `mouthGrob` does for `smile` and so on.

https://github.com/Selbosh/ggChernoff/blob/5369b46e747e9303c2b899e393c54014993587b7/R/chernoffGrob.R#L38

One would then add a corresponding `scale_eyes_continuous()` function.

If you're not confident doing this then I can add this feature for you.
